- type: entity
  id: PaperPrinterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: paper printer machine board
  components:
  - type: MachineBoard
    prototype: PaperPrinter
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterCommandMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: command paper printer machine board
  components:
  - type: Sprite
    state: command
  - type: MachineBoard
    prototype: PaperPrinterCommand
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: security paper printer machine board
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: PaperPrinterSecurity
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterEngineeringMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: engineering paper printer machine board
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: PaperPrinterEngineering
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterMedicalMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: medical paper printer machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: PaperPrinterMedical
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterSupplyMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: cargo paper printer machine board # Ronstation - while it may sound counterintuitive to name it 'supply', it is necessary, in my opinion, for standardization purposes.
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: PaperPrinterSupply
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterScienceMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: science paper printer machine board
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: PaperPrinterScience
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterServiceMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: service paper printer machine board
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: PaperPrinterService
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterCaptainMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: captain's paper printer machine board
  components:
  - type: Sprite
    state: command
  - type: MachineBoard
    prototype: PaperPrinterCaptain
    stackRequirements:
      Manipulator: 3

- type: entity
  id: PaperPrinterHeadOfPersonnelMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: head of personnel's paper printer machine board
  components:
  - type: Sprite
    state: command
  - type: MachineBoard
    prototype: PaperPrinterHeadOfPersonnel
    stackRequirements:
      Manipulator: 3
