- type: job
  id: BlueshieldOfficer
  name: job-name-blueshield-officer
  description: job-description-blueshield-officer
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Bar
  - Blueshield
  - Brig
  - Cargo
  - Chapel
  - Command
  - Cryogenics
  - Engineering
  - External
  - Hydroponics
  - Janitor
  - Kitchen
  - Lawyer
  - Maintenance
  - Medical
  - Service
  - Theatre
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCommand
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    - WeaponPistolMk58
    - MagazinePistol

- type: chameleonOutfit
  id: BlueshieldOfficerOutfit
  job: BlueshieldOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretBlueshield
    mask: ClothingMaskGasSecurity
    neck: Dinkyshield
    gloves: ClothingHandsGlovesColorBlack
