- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  #- Reach
  - Exo
  - Saltern2
  - Cluster2
  #- Atlas2 # Ronstation - Derotated for the time being until enough rework is made.
